name: flutter_foodpage_plugin
description: A Flutter package was created by Foodpage to manage Foodpage's APIs and features.
version: 1.0.0
homepage: https://github.com/hashcode404/flutter_foodpage_plugin


environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  #network
  dio: ^5.1.1
  socket_io_client: ^2.0.3+1

  
  #storage
  shared_preferences: ^2.1.0

  # Utils
  flutter_gen: ^5.5.0+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_fancy_tree_view: ^1.6.0
  intl: ^0.18.1
  html: ^0.15.1
  flutter_treeview: ^1.0.7+1
  fluttertoast: ^8.2.6
  
  # Icons
  fluentui_system_icons: ^1.1.239
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0

  # State Management
  provider: ^6.1.2


  # Animation
  lottie: ^3.1.2

  # AI
  flutter_gemini: ^2.0.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.10



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
